# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = SusyWeakProdAna
PACKAGE_PRELOAD  = Tree
PACKAGE_CXXFLAGS = -DDEBUG -g
PACKAGE_LDFLAGS  = $(shell root-config --libs)
PACKAGE_BINFLAGS = -lCintex -lReflex -lPyROOT -lXMLParser -lEG 
PACKAGE_DEP      = ReweightUtils Mt2 SusyNtuple SusyMatrixMethod ChargeFlip
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common
